title: maisy moon
baseURL: /
params:
  palette: yellow
  header:
    title: maisy moon
    tagline: ""
    logo_img: /images/mm-logo.png
    bg_img: /images/screen-shot-2020-05-10-at-4.43.59-pm.jpg
    has_nav: true
    has_social: false
  footer:
    content: "&copy; All rights reserved."
    links:
      - text: Maisy Moon
        url: ""
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
