title: maisy moon
baseURL: /
params:
  palette: yellow
  header:
    title: maisy moon
    tagline: dis dat coo cool site
    logo_img: images/logo.png
    bg_img: /images/mm-menu.jpg
    has_nav: true
    has_social: false
  footer:
    content: "&copy; All rights reserved."
    links:
      - text: Maisy Moon
        url: ""
        new_window: true
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
